"""Section 2, Literature Review.

Each cited work is summarised from its abstract and conclusions and then tied
back to a specific component of the pipeline evaluated here, so the review
functions as an argument about this system rather than as an annotated
bibliography. Every citation key resolves through article_refs, which is built
from CrossRef/DataCite metadata; make_article.py fails the build if any key is
unresolved or if any resolved reference goes uncited.
"""
from article_refs import cite, citet
from article_style import h1, h2, para

# ruff: noqa: E501


def build():
    B = [h1("2. Literature Review")]
    p = lambda t: B.append(para(t))                      # noqa: E731

    # ------------------------------------------------- 2.1
    B.append(h2("2.1 Active and Passive Video Forensics"))
    p("Media forensics divides along the question of whether the "
      "authentication signal is inserted before distribution or recovered "
      "afterwards. Active methods embed a watermark or a cryptographic "
      "signature at capture time and verify it later. They are exact when "
      "they apply, and they almost never apply: the overwhelming majority of "
      "video in circulation was captured by devices that embed nothing, "
      "transcoded by platforms that strip what little metadata survives, and "
      "redistributed through channels that re-encode aggressively. Passive "
      "methods make no such demand. They treat the video as the only "
      "evidence and look for statistical inconsistency introduced by the "
      "manipulation itself.")
    p(citet("verdoliva") + " frames the modern field in exactly these terms "
      "and argues that the passive problem has changed character with the "
      "arrival of learned synthesis: the artefacts that classical passive "
      "forensics targeted were byproducts of editing operations, whereas the "
      "artefacts left by a generative model are byproducts of the model's "
      "own inductive bias and shift whenever the model changes. "
      + citet("mirsky") + " surveys both the creation and the detection side "
      "and reaches a compatible conclusion: because generator and detector "
      "improve against each other, a detector's value depends more on "
      "whether its cue is intrinsic to the manipulation than on the score it "
      "reaches against the generation of generators it was trained on. "
      + citet("sitara") + " provides the corresponding overview for "
      "conventional video tampering, cataloguing the passive techniques "
      "available for double compression, region duplication and temporal "
      "manipulation.")
    p("The system evaluated in the present paper is unambiguously passive, "
      "and it makes the intrinsic-cue argument explicitly: its design "
      "rationale is that temporal inconsistency is a property of frame-wise "
      "synthesis rather than of a particular synthesiser. Whether the "
      "implementation realises that rationale is an empirical question, and "
      "Section 5 answers it.")

    # ------------------------------------------------- 2.2
    B.append(h2("2.2 Handcrafted Statistical Traces"))
    p("The oldest strand of passive forensics builds explicit statistical "
      "descriptors and tests them for the disturbance a manipulation would "
      "cause. " + citet("haralick") + " introduced the grey-level "
      "co-occurrence matrix, which characterises texture by tabulating how "
      "often pairs of grey levels occur at a fixed spatial offset and "
      "reducing that tabulation to contrast, correlation, energy and "
      "homogeneity. The descriptor is cheap, interpretable and remarkably "
      "durable: it remains a standard baseline in image forgery work fifty "
      "years after publication, and it appears in the present cohort as the "
      "GLCM comparison model.")
    p(citet("popescu") + " showed that resampling — the interpolation any "
      "geometric transformation performs — introduces periodic correlations "
      "among neighbouring pixels that can be recovered by an "
      "expectation-maximisation estimator, giving a detector for scaled or "
      "rotated spliced regions that requires no training data at all. "
      + citet("fridrich") + " generalised the idea of hand-designed residual "
      "statistics into rich models: large ensembles of quantised, truncated "
      "co-occurrence features over multiple high-pass residuals, which "
      "dominated steganalysis and transferred effectively to splicing "
      "detection. " + citet("wang2009") + " analysed double quantisation in "
      "compressed video and showed that re-encoding after editing leaves a "
      "recoverable signature in the distribution of transform coefficients.")
    p("In the temporal domain, " + citet("kingra") + " combined motion and "
      "brightness gradients to expose frame insertion and deletion in H.264 "
      "streams, and " + citet("fadl") + " used histograms of oriented "
      "gradients over motion energy images for the same family of attacks. "
      + citet("shelke") + " extended the approach with a VGG-16 feature "
      "extractor and kernel PCA, reporting strong results for multiple "
      "simultaneous forgery types. These works matter here for a specific "
      "reason: they establish that temporal-domain manipulation leaves "
      "recoverable traces in first-order difference statistics. The "
      "representation search reported in Section 5.7 of this paper arrives "
      "independently at the same family of descriptors as the only one that "
      "carries signal on this corpus, which is a small but genuine point of "
      "contact between the classical and the learned literature.")

    # ------------------------------------------------- 2.3
    B.append(h2("2.3 Frame-level Convolutional Detectors"))
    p("The first generation of learned deepfake detectors treated the "
      "problem as per-frame image classification and aggregated frame scores "
      "by averaging. " + citet("mesonet") + " deliberately kept the network "
      "shallow, arguing that the discriminative artefacts live at a "
      "mesoscopic scale between fine texture and semantic content, and that "
      "a deep network trained on a small corpus would memorise identities "
      "rather than artefacts. The resulting architecture is small enough to "
      "train on modest hardware and remains a standard reference point.")
    p(citet("faceforensics") + " released the benchmark that reoriented the "
      "field, providing 1,000 original sequences manipulated by four methods "
      "at three compression levels, and — more consequentially for practice "
      "— demonstrating that a fine-tuned Xception network "
      + cite("xception") + " restricted to the face region outperformed both "
      "handcrafted baselines and human observers by a wide margin. That "
      "result established the template most subsequent work follows: crop "
      "the face, fine-tune a strong ImageNet backbone, aggregate over "
      "frames.")
    p(citet("capsule") + " replaced the standard classifier head with a "
      "capsule network, using dynamic routing to model part-whole "
      "relationships that a flat softmax discards, and reported improved "
      "robustness to compression. " + citet("facexray") + " made a different "
      "and influential argument: rather than learning the signature of any "
      "particular generator, learn to detect the blending boundary that all "
      "face-swap pipelines must produce when compositing a synthesised face "
      "into a real frame. Because the blending step is common to methods "
      "that differ entirely in their generators, the resulting detector "
      "generalises across manipulation types far better than a "
      "generator-specific one.")
    p("Frequency-domain variants pursue the same generalisation goal through "
      "a different channel. " + citet("qian_f3net") + " decomposed inputs "
      "with a learnable frequency-aware filter bank and showed that "
      "upsampling operations inside generators leave characteristic "
      "high-frequency signatures. " + citet("luo_hf") + " combined "
      "high-frequency residuals with RGB content in a two-stream design and "
      "demonstrated substantially improved cross-dataset transfer. "
      + citet("coccomini") + " showed that pairing an EfficientNet feature "
      "extractor with a vision transformer aggregator is competitive with "
      "far heavier ensembles on the DFDC corpus.")
    p("Two systematic reviews map this family in detail and are worth "
      "consulting for their aggregate observations rather than for any "
      "individual method. " + citet("rana") + " reviewed 112 primary "
      "studies published between 2018 and 2020 and classified them by "
      "approach, reporting that deep-learning methods dominate numerically "
      "while a substantial minority remain statistical or feature-based, and "
      "noting that reported accuracies cluster tightly near the top of the "
      "scale in a way that makes cross-study comparison nearly meaningless "
      "because protocols, splits and corpora differ. " + citet("yu_survey")
      + " reached a compatible conclusion for video specifically, "
      "organising detection methods by the cue they exploit — spatial "
      "artefact, temporal inconsistency, biological signal, and "
      "frequency-domain trace — and identifying generalisation across "
      "manipulation methods, robustness to compression, and the absence of "
      "standardised evaluation as the three open problems. The present "
      "paper is a direct response to the third of those: it fixes the "
      "protocol, publishes the code that produces every number, and reports "
      "what that protocol gives even where the answer is unflattering.")
    p("The common limitation of this family is structural rather than "
      "incidental: a per-frame classifier cannot, even in principle, observe "
      "an inconsistency that only exists between frames. Averaging frame "
      "scores discards precisely the joint structure that distinguishes a "
      "sequence of individually plausible faces from a plausible sequence of "
      "faces. This paper measures that limitation directly. The "
      "time-collapsed reference representation described in Section 5.5 "
      "reaches an area under the ROC curve of 0.5230, statistically "
      "indistinguishable from chance, while the same features preserved as "
      "frame-to-frame differences reach 0.7307.")

    # ------------------------------------------------- 2.4
    B.append(h2("2.4 Temporal and Spatiotemporal Modelling"))
    p("The video-understanding literature supplies the architectural "
      "vocabulary that forgery detection borrows. " + citet("c3d") + " "
      "established that three-dimensional convolution learns appearance and "
      "motion jointly and that comparatively small 3x3x3 kernels are the "
      "effective choice, which is the design the trunk of the model studied "
      "here adopts. " + citet("i3d") + " showed that inflating "
      "two-dimensional kernels from a pre-trained image network into three "
      "dimensions preserves the benefit of large-scale image pre-training, "
      "removing the main practical objection to 3D convolution. "
      + citet("slowfast") + " decomposed the problem into a slow pathway for "
      "semantics and a fast pathway for motion, an explicit acknowledgement "
      "that spatial and temporal evidence have different natural sampling "
      "rates. " + citet("lstm") + " remains the standard recurrent "
      "aggregator, and the two-layer recurrent stage in the network studied "
      "here is a direct instance of it.")
    p("Applied to forgery detection, " + citet("guera") + " combined a "
      "convolutional feature extractor with an LSTM over frame features and "
      "reported that sequences as short as twenty frames suffice to separate "
      "manipulated from authentic video — an early and clean demonstration "
      "that the temporal axis carries the discriminative information. "
      + citet("sabir") + " refined this with face alignment and recurrent "
      "convolutional strategies, showing that the recurrent stage benefits "
      "materially from geometric normalisation of the input crops.")
    p(citet("amerini") + " approached the temporal axis through optical "
      "flow, training a convolutional classifier on flow fields rather than "
      "on pixels, on the grounds that a frame-wise generator has no "
      "mechanism enforcing consistent apparent motion. "
      + citet("haliassos") + " pushed the idea furthest: a network "
      "pre-trained for visual speech recognition, and therefore already in "
      "possession of a model of natural mouth dynamics, transfers to forgery "
      "detection with far better cross-manipulation generalisation than a "
      "detector trained from scratch on forgery labels. "
      + citet("ftcn") + " reached a similar conclusion by architectural "
      "means, showing that suppressing spatial capacity while retaining "
      "long-range temporal modelling improves generalisation — the spatial "
      "pathway, in other words, is where overfitting to the generator "
      "happens.")
    p(citet("stil") + " is the work most directly relevant to the present "
      "study, and its modules are evaluated here unmodified. It decomposes "
      "spatiotemporal inconsistency into two cooperating components. The "
      "Temporal Inconsistency Module splits the channel dimension, shifts "
      "one part along the temporal axis, differences it against the "
      "unshifted part, and learns an attention map over the resulting "
      "difference tensor, so that the network is presented with frame-to-"
      "frame change as a first-class input rather than having to infer it. "
      "The Information Supplement Module restores spatial detail that the "
      "differencing operation removes. Reported results on FaceForensics++ "
      "and Celeb-DF are competitive with much larger models at a fraction "
      "of the parameter count. " + citet("stidnet") + " combines "
      "spatiotemporal modelling with identity-aware knowledge distillation, "
      "and gives its name to one of the comparison models in the released "
      "cohort studied here.")
    p("Transformer formulations followed. " + citet("istvt") + " introduced "
      "a decomposed spatial-temporal self-attention with a self-subtract "
      "mechanism, explicitly building the temporal difference into the "
      "attention operator, and provided interpretability maps showing which "
      "regions and which frames drive each decision. " + citet("tall") + " "
      "took an unusual and effective route, tiling a video clip into a "
      "single thumbnail-layout image so that an ordinary image transformer "
      "sees spatial and temporal structure simultaneously; the method "
      "reports state-of-the-art or comparable results on intra-dataset, "
      "cross-dataset and diffusion-generated evaluations. "
      + citet("gaze") + " analysed spatial-temporal gaze inconsistency, "
      "arguing that gaze trajectory is a physiological regularity that "
      "current generators do not model and therefore a cue with unusually "
      "good transfer properties. " + citet("vaswani") + " and "
      + citet("vit") + " supply the underlying attention and vision-"
      "transformer machinery these methods build on.")
    p("Taken together this literature makes a strong and consistent claim: "
      "the temporal axis is where the recoverable evidence lives, and "
      "architectures that model it explicitly outperform those that do not. "
      "The empirical section of this paper tests that claim on the present "
      "corpus in two ways — by evaluating STIL's own modules on the cached "
      "tensors, and by comparing a time-collapsed representation against a "
      "temporal-difference representation of the identical features.")

    # ------------------------------------------------- 2.5
    B.append(h2("2.5 Attention Mechanisms and the SCAM/MUSE Lineage"))
    p("Both attention blocks in the model studied here descend from an "
      "identifiable line of work, and understanding that line is necessary "
      "to interpret the ablation results in Section 5.")
    p(citet("senet") + " introduced channel attention in its modern form: "
      "pool each feature map to a scalar, pass the resulting vector through "
      "a bottleneck multilayer perceptron, and use the sigmoid output to "
      "rescale the channels. The block adds negligible computation and "
      "improved every backbone it was added to, which is why it propagated "
      "so quickly. " + citet("cbam") + " added the complementary spatial "
      "branch — pool across channels rather than across space, convolve the "
      "resulting two-channel map with a large kernel, and gate spatially — "
      "and applied the two branches in sequence. The SCAM module in the "
      "network studied here is a joint spatial-and-channel formulation of "
      "exactly this design, and the implementation follows CBAM's structure "
      "closely: global average and max pooling into a shared MLP for the "
      "channel gate, channel-wise average and max into a large-kernel "
      "convolution for the spatial gate.")
    p(citet("nonlocal") + " provided the other half of the vocabulary, "
      "generalising self-attention to a non-local operator that relates "
      "every position to every other position in space and time, and "
      "demonstrating that a small number of such blocks substantially "
      "improves video recognition. " + citet("mat") + " applied multi-"
      "attentional design specifically to deepfake detection, arguing that "
      "forgery detection is a fine-grained classification problem in which "
      "multiple attention heads should attend to different local regions, "
      "and combining that with textural feature enhancement.")
    p("There is a further reason to be careful about attention modules "
      "specifically, which the ablation in Section 5.3 illustrates. An "
      "attention block is a multiplicative gate: it produces coefficients in "
      "(0, 1) and rescales its input by them. If the features arriving at "
      "the gate carry no class-discriminative structure, the gate has "
      "nothing to select and its output is a smoothly rescaled copy of a "
      "signal that was already uninformative. The block does not fail "
      "loudly in that situation — it trains without error, its gradients are "
      "well behaved, and its coefficients settle to plausible-looking values "
      "— so its presence in an architecture diagram is no evidence that it "
      "contributed. This is why an attention ablation must be read together "
      "with an absolute measure of whether the surrounding model learned at "
      "all, and why the tables in Section 5 pair every ablation figure with "
      "the specificity of the same run.")
    p("The MUSE block in the studied network is a multi-excitation module "
      "operating on the 128-dimensional recurrent state: several excitation "
      "paths are computed and combined by averaging, with an ELU "
      "nonlinearity and light dropout " + cite("dropout") + ". "
      "Architecturally it is a squeeze-and-excitation variant applied after "
      "temporal aggregation rather than within the convolutional trunk.")
    p("This lineage sets a clear expectation for the ablation. Both blocks "
      "are, in the literature they come from, reliable small improvements. "
      "If neither the SCAM-only nor the MUSE-only variant differs "
      "measurably from the full model, and if none of the three differs "
      "measurably from a constant classifier, the natural inference is not "
      "that attention is useless in general but that no gradient signal "
      "reached the blocks — that the pipeline never learned anything for "
      "them to modulate. Section 5.3 reports exactly this pattern.")

    # ------------------------------------------------- 2.6
    B.append(h2("2.6 Modern Backbones as Reference Points"))
    p("A re-evaluation is only informative if the comparison set is strong. "
      "The four backbones added to the cohort in this study were chosen to "
      "span distinct architectural families and to postdate the models in "
      "the released comparison set by several years.")
    p(citet("resnet") + " established residual learning, without which none "
      "of the others exist. " + citet("resnetrs") + " revisited that "
      "architecture with modernised training and scaling recipes and showed "
      "that a substantial fraction of the improvement attributed to newer "
      "architectures was in fact attributable to training procedure — a "
      "result with direct methodological relevance here, since it implies "
      "that architecture comparisons under a fixed and short training budget "
      "measure something other than architecture quality. "
      + citet("efficientnet") + " introduced compound scaling of depth, "
      "width and resolution, and " + citet("efficientnetv2") + " improved "
      "its training speed and parameter efficiency with fused convolutions "
      "and progressive learning. " + citet("mobilenetv3") + " combined "
      "architecture search with hardware-aware design and squeeze-and-"
      "excitation blocks to produce a family targeted at constrained "
      "devices. " + citet("convnext") + " modernised a pure convolutional "
      "design using the training recipe and macro-design choices of vision "
      "transformers, and matched transformer accuracy without attention.")
    p("Each of these is used here as a frozen feature extractor followed by "
      "a trained head, which is the standard transfer-learning protocol for "
      "small corpora and the one most likely to succeed given fifty "
      "training videos. Their inclusion answers an obvious objection to any "
      "negative result: that the models in the released cohort are simply "
      "dated.")
    p("A caveat applies to all four, and it follows directly from "
      + citet("resnetrs") + ". These backbones were pre-trained on natural "
      "photographs of objects and scenes, and the invariances they acquired "
      "in that regime — to illumination, viewpoint, scale and mild texture "
      "perturbation — are precisely the invariances a forgery detector must "
      "not have, since blending seams and resampling residuals are exactly "
      "the kind of low-level perturbation ImageNet training teaches a "
      "network to discard. This is a known tension in the field and is part "
      "of why " + citet("qian_f3net") + " and " + citet("luo_hf") + " "
      "reintroduce high-frequency content explicitly. Frozen-backbone "
      "transfer is therefore a strong baseline in the sense of being "
      "well-trained and well-understood, but not in the sense of being "
      "purpose-built. Their role in this study is to establish that the "
      "measured ceiling is not an artefact of the released cohort's age, and "
      "the results in Section 5.2 show they do not clear it either.")

    # ------------------------------------------------- 2.7
    B.append(h2("2.7 Metaheuristic Optimisation in Forensic Pipelines"))
    p("The released project tunes its proposed model with a population-based "
      "metaheuristic drawn from the MEALPY library " + cite("mealpy") + ", "
      "which collects a large number of nature-inspired optimisers behind a "
      "common interface. Metaheuristic hyperparameter tuning is widespread "
      "in applied forensics papers, and it carries two well-understood "
      "risks that are worth stating explicitly because both are visible in "
      "this project.")
    p("The first is theoretical. " + citet("nfl") + " proved that averaged "
      "over all objective functions no search algorithm outperforms any "
      "other, so a metaheuristic's advantage on a particular problem is a "
      "claim about the match between the algorithm's bias and that "
      "problem's structure — a claim requiring evidence rather than a "
      "property the algorithm carries with it. The second is procedural. A "
      "population-based search evaluates hundreds of candidate "
      "configurations; if the fitness function evaluates on the data later "
      "used for reporting, the search is a highly efficient mechanism for "
      "selecting the configuration that best fits that particular sample, "
      "which is the selection bias " + citet("cawley") + " analyses. When "
      "the fitness function is additionally computed by a tampered metric, "
      "the search optimises the tampering. Section 5.2 reports the "
      "metaheuristically tuned variant under the corrected protocol.")
    p("There is also a question of evidential value that applies regardless "
      "of protocol. A metaheuristic search over a discrete hyperparameter "
      "grid on a fifty-video corpus evaluates its candidates against an "
      "objective whose sampling noise, by the analysis of "
      + citet("varoquaux") + " and " + citet("bouthillier") + ", exceeds "
      "the differences between most of the candidates. Under those "
      "conditions the search converges reliably — populations always "
      "converge — but what it converges to is the configuration that "
      "happened to suit the particular resampling draws it was scored on. "
      "Re-running the same search under a different seed selects a "
      "different configuration with an equally good reported fitness. The "
      "appropriate response is not to abandon the search but to report the "
      "spread across seeds rather than the best single outcome, and to "
      "select the configuration inside the training folds so that the "
      "reported score is at least unbiased. The protocol used in Section 5 "
      "does the latter; the original work does neither.")

    # ------------------------------------------------- 2.8
    B.append(h2("2.8 Evaluation Methodology for Small Corpora"))
    p("The corpus in this project contains fifty videos. That number governs "
      "what any experiment on it can establish, and the methodological "
      "literature on small-sample evaluation is therefore not a "
      "supplementary concern but the central one.")
    p(citet("varoquaux") + " measured the sampling distribution of "
      "cross-validated accuracy directly and found error bars of tens of "
      "percentage points at sample sizes typical of neuroimaging studies, "
      "concluding that cross-validation on small samples produces estimates "
      "too noisy to rank methods. " + citet("vabalas") + " reached the same "
      "conclusion for clinical prediction and showed additionally that "
      "several commonly used validation schemes produce biased estimates at "
      "small n even when applied as intended. " + citet("bouthillier") + " "
      "showed that the variance introduced by nuisance factors — "
      "initialisation seed, data ordering, augmentation randomness — "
      "typically exceeds the improvements claimed in benchmark papers, and "
      "recommended reporting across many such sources of variation.")
    p(citet("combrisson") + " addressed the specific and frequently "
      "overlooked question of what chance means. On small or imbalanced "
      "samples the empirical distribution of accuracy under a true null "
      "hypothesis is wide and centred above the nominal chance rate, so "
      "comparing an observed score to 50% is not a test. "
      + citet("ojala") + " gave the corresponding remedy: permute the "
      "labels, re-run the complete procedure, and compare the observed "
      "score to the resulting empirical null. This paper uses that test "
      "throughout, with 200 permutations of the full nested procedure.")
    p(citet("brodersen") + " analysed balanced accuracy and its posterior "
      "distribution, showing that on imbalanced data plain accuracy is "
      "systematically optimistic and that the balanced form is the "
      "appropriate summary. " + citet("he_imbalance") + " surveys learning "
      "from imbalanced data more broadly, and " + citet("saito") + " "
      "demonstrates that precision-recall analysis is more informative than "
      "ROC analysis when the positive class is rare. These matter acutely "
      "here: on a 29/21 corpus a classifier that answers 'authentic' for "
      "every input scores 58% accuracy and an F1 above 73, numbers that read "
      "as a working detector and are produced by a model that has learned "
      "nothing. Section 5 therefore reports specificity and balanced "
      "accuracy beside every accuracy figure, precisely so that this failure "
      "mode is visible rather than hidden.")
    p(citet("hanley") + " established the interpretation of the area under "
      "the ROC curve as the probability that a randomly chosen positive "
      "outranks a randomly chosen negative, together with its standard "
      "error — the basis for the accuracy ceiling computed in Section 5.6. "
      + citet("demsar") + " set out how classifiers should be compared "
      "across multiple datasets, and his central warning applies directly to "
      "single-corpus studies: differences smaller than the resampling noise "
      "are not findings.")

    # ------------------------------------------------- 2.9
    B.append(h2("2.9 Leakage, Reproducibility and Research Integrity"))
    p(citet("ioannidis") + " gave the field-independent argument that in "
      "research areas combining small samples, small effects, analytic "
      "flexibility and strong incentives, the majority of published positive "
      "findings will be false. Every one of those four conditions holds for "
      "small-corpus forgery detection.")
    p(citet("kapoor") + " provided the machine-learning-specific version, "
      "auditing 294 papers across seventeen fields and finding data leakage "
      "in a large fraction of them, with a taxonomy that names the exact "
      "failures relevant here: no clean separation between training and test "
      "data, preprocessing performed on the full dataset before splitting, "
      "feature selection using test labels, and model selection on the "
      "reporting set. " + citet("gundersen") + " surveyed reproducibility "
      "in artificial intelligence research and found that a small minority "
      "of papers document enough to permit independent reproduction, with "
      "code and data availability the most common gaps. "
      + citet("cawley") + " supplies the quantitative core: selection bias "
      "in performance evaluation, arising when the same data both selects "
      "and scores, is large enough to invert published rankings.")
    p("Two practical consequences follow for reproduction attempts, and both "
      "are adopted as working procedure in this study. The first is that "
      "a released metric implementation must be treated as an untrusted "
      "input until it has been checked. The check is inexpensive: construct "
      "label and prediction vectors whose confusion matrix is known by "
      "hand, pass them through the project's own scoring path, and compare. "
      "A metric that alters its inputs fails this immediately. The second is "
      "that stored result files should be checked for internal consistency "
      "against the corpus they claim to describe — a confusion matrix whose "
      "entries do not sum to a possible test-partition size, or an accuracy "
      "quoted to more significant figures than the sample size can support, "
      "is evidence of a computation that did not occur. Both checks found "
      "defects in the material examined here, and neither requires access "
      "to anything beyond the released repository.")
    p("What this literature does not directly address is the case found "
      "here, where the defect is neither leakage nor optimistic protocol "
      "design but a modification to the scoring function itself. That case "
      "is qualitatively worse, because every methodological safeguard the "
      "above literature recommends operates on the protocol and none of them "
      "inspects the metric. A study can use nested cross-validation "
      "faithfully, hold out its test set scrupulously, permute its labels "
      "conscientiously — and still report fabricated numbers, if the "
      "function computing the confusion matrix has been altered. The "
      "practical conclusion, and one of the recommendations of this paper, "
      "is that verifying the metric implementation against a reference "
      "library on synthetic inputs with known confusion matrices should be a "
      "routine step in any reproduction attempt.")

    # ------------------------------------------------- 2.10
    B.append(h2("2.10 Corpora, Protocols and What They Do and Do Not Fix"))
    p("The corpora that anchor this literature deserve separate treatment, "
      "because the protocol conventions they established are what a "
      "small-corpus study silently departs from.")
    p(citet("faceforensics") + " released 1,000 source sequences manipulated "
      "by four methods and distributed at three compression levels, with a "
      "fixed 720/140/140 split into training, validation and test "
      "partitions defined at the level of source identities rather than of "
      "clips. That last detail is the important one: because a manipulated "
      "sequence shares its underlying footage with the original it was "
      "derived from, splitting at the clip level would place near-duplicate "
      "material on both sides of the boundary, and a detector could then "
      "score highly by recognising the footage rather than the manipulation. "
      "The identity-level split exists specifically to prevent this. "
      + citet("celebdf") + " went further, arguing that the visible "
      "artefacts in earlier corpora were severe enough that detectors "
      "trained on them learned artefact signatures with no counterpart in "
      "circulated material, and released a corpus with substantially "
      "improved synthesis quality on which every method then published lost "
      "a large fraction of its accuracy. " + citet("dfdc") + " contributed "
      "scale and diversity of subjects and capture conditions, and "
      + citet("deeperforensics") + " added deliberate real-world "
      "perturbations — compression, noise, colour shift and blur — applied "
      "at graded severities so that robustness could be measured rather "
      "than assumed.")
    p("Three conventions follow from that history and are near-universal in "
      "the corpora-based literature: split by identity and not by clip, "
      "report on a corpus other than the training one, and report at graded "
      "perturbation severities. A study that samples fifty clips out of such "
      "a corpus into a flat pool and then applies stratified k-fold "
      "cross-validation to that pool departs from all three at once. The "
      "first departure is the dangerous one, since it risks the exact "
      "footage-recognition failure the identity-level split was designed to "
      "prevent, and it would inflate every score in this study rather than "
      "deflate them. This paper therefore tests for it directly: Section 5.6 "
      "reports a pairwise similarity audit across all 1,225 video pairs in "
      "the corpus, and finds no pair above the near-duplicate threshold. "
      "The measured performance is consequently low for reasons other than "
      "leakage, which is the harder and more informative of the two "
      "possibilities.")

    # ------------------------------------------------- 2.11
    B.append(h2("2.11 Research Gaps and Positioning"))
    p("Four gaps emerge from the review, and this paper addresses each.")
    p("First, the spatiotemporal detection literature reports results almost "
      "exclusively on corpora of thousands to hundreds of thousands of "
      "clips, while a large applied literature reports comparable or higher "
      "accuracies on corpora of tens of clips. The methodological literature "
      "of Section 2.8 implies that the latter cannot be measuring the same "
      "thing. What is missing is a study that takes a small-corpus pipeline "
      "and determines empirically what it can support, rather than assuming "
      "the answer in either direction. Sections 5.5 and 5.6 supply that "
      "determination for this pipeline: an out-of-fold area under the ROC "
      "curve of 0.7307, and an accuracy ceiling of 74.00% attainable at the "
      "best threshold on that very curve.")
    p("Second, ablation studies of attention modules are almost never "
      "accompanied by a check that the surrounding model learned anything at "
      "all. An ablation is only interpretable if the full model works; "
      "otherwise the ablation compares two constant classifiers. Section 5.3 "
      "reports the ablation together with the specificity that makes its "
      "interpretation unambiguous.")
    p("Third, comparisons against published baselines are usually made "
      "against numbers quoted from the original papers, computed on "
      "different corpora under different protocols. Section 6 instead "
      "re-measures every comparison model on identical splits with identical "
      "scoring, and reports literature figures separately and explicitly as "
      "context rather than as a comparison.")
    p("Fourth, and most specifically, no published work evaluates the "
      "modules of a strong spatiotemporal detector on the feature "
      "representation used by a competing small-corpus pipeline. Doing so "
      "separates two hypotheses that are otherwise confounded: that the "
      "pipeline underperforms because its architecture is weak, or that it "
      "underperforms because its representation does not carry the signal. "
      "Section 5.9 reports the Temporal Inconsistency and Information "
      "Supplement modules of " + citet("stil") + ", imported without "
      "modification from the authors' repository, applied to the cached "
      "tensors of this project.")
    p("A fifth observation cuts across all four. The reviewed literature "
      "contains, on one side, methods evaluated on corpora three to four "
      "orders of magnitude larger than the one used here, with "
      "identity-level splits, cross-corpus reporting and graded robustness "
      "analysis; and on the other, a large applied literature reporting "
      "equal or higher accuracies on a few dozen clips with none of those "
      "safeguards. The two bodies of work cite each other freely and are "
      "read as commensurable, but by the analysis of Sections 2.8 and 2.10 "
      "they are not measuring the same quantity, and a number from the "
      "second cannot be placed in a table beside a number from the first. "
      "Section 6 of this paper therefore separates the two explicitly: "
      "measured results on identical splits appear in one table, "
      "author-reported literature figures in another, and the text states "
      "what each can and cannot support. This separation is unusual, and it "
      "is the single change most likely to be useful to other small-corpus "
      "studies regardless of what they find.")
    p("The positioning of this paper follows from those gaps. It is a "
      "re-measurement and characterisation study rather than an "
      "architecture-proposal study. Its contribution is a defensible answer "
      "to the question of what this corpus and this representation support, "
      "an audit trail for the fabricated material it replaces, and a "
      "protocol that other small-corpus forensic studies can adopt directly.")
    p("What follows is organised to make that answer checkable rather than "
      "merely stated. Section 3 describes the model and the pipeline as they "
      "exist in the source, with the layer shapes recomputed from the cached "
      "tensor rather than transcribed. Section 4 fixes the protocol before "
      "any result is shown. Section 5 reports every measurement, including "
      "those that contradict the original claims and those that contradict "
      "the expectations set by the literature reviewed above.")
    return "".join(B)
