"""Section 1, Introduction.

Prose only. Every numeric claim is repeated from the JSON and .npy artefacts in
Analysis1/ and Optimized/, and make_article.py asserts the important ones
against those files at build time so the text cannot drift away from the runs.
"""
from article_refs import cite, citet
from article_style import bullet, h1, h2, para

# ruff: noqa: E501


def build():
    B = [h1("1. Introduction")]
    p = lambda t: B.append(para(t))                      # noqa: E731

    # ------------------------------------------------- 1.1
    B.append(h2("1.1 The Evidentiary Status of Digital Video"))
    p("Digital video occupies a peculiar position in contemporary evidentiary "
      "practice. It is simultaneously the most persuasive and the least "
      "verifiable class of record in wide circulation. A recording of an "
      "event carries an intuitive authority that a transcript or a still "
      "photograph does not: it appears to show duration, causality and "
      "context together, and a viewer who watches a clip believes they have "
      "witnessed something rather than been told about it. Courts admit video "
      "as demonstrative evidence, newsrooms treat it as corroboration, "
      "insurers settle claims on the strength of dashcam footage, and "
      "regulators increasingly accept video attestation in place of physical "
      "presence. In each of these settings the assumption underneath the "
      "practice is that fabricating convincing video is expensive enough, and "
      "requires enough specialist skill, that the base rate of manipulation "
      "is low.")
    p("That assumption has stopped holding. Face-replacement toolkits with "
      "graphical front-ends, publicly released generative models, and "
      "commodity accelerator hardware have jointly reduced the cost of a "
      "convincing manipulation from a studio budget to an evening of work by "
      "a motivated amateur. The technical literature has responded with a "
      "substantial detection effort, surveyed comprehensively by "
      + citet("mirsky") + ", " + citet("verdoliva") + ", "
      + citet("nguyen_survey") + " and " + citet("masood") + ", and the "
      "public benchmarks that anchor that effort — FaceForensics++ "
      + cite("faceforensics") + ", Celeb-DF " + cite("celebdf") + ", the "
      "DeepFake Detection Challenge corpus " + cite("dfdc") + " and "
      "DeeperForensics " + cite("deeperforensics") + " — have grown from "
      "thousands to hundreds of thousands of clips. Reported accuracies on "
      "these benchmarks routinely exceed 95%, and on the easier "
      "high-quality splits they exceed 99%.")
    p("The gap between those numbers and the observed reliability of "
      "deployed detectors is the central practical problem of the field. A "
      "detector that reports 99% on a within-dataset split and then fails on "
      "a manipulation method it has not seen is not merely disappointing; it "
      "is actively harmful, because the reported figure is what a "
      "non-specialist decision-maker will rely on. The forensic value of a "
      "detector is not its peak benchmark score but the trustworthiness of "
      "the number attached to it. This paper is, in the end, about that "
      "second quantity.")
    p("There is a structural reason the two diverge, and it is worth naming "
      "before any experiment is described. A benchmark score answers the "
      "question: given a video drawn from the same distribution as the "
      "training data, how often is the label correct? A deployment needs the "
      "answer to a different question: given this video, whose provenance is "
      "unknown and whose manipulation method may postdate the detector, how "
      "much should the reported label move a decision? The first question "
      "has a single number as its answer and the second does not. It "
      "requires, at minimum, a calibrated probability, an interval around "
      "it, and an explicit statement of the conditions under which the "
      "estimate was obtained. Almost none of the published detection "
      "literature supplies all three, and the pipeline examined in this "
      "paper supplies none of them.")
    p("The consequence is that a forensic claim built on a detector output "
      "inherits an uncertainty that was never quantified. When the "
      "underlying corpus contains fifty videos, that omission is not a "
      "refinement to be added later; it is the difference between a result "
      "and a coincidence. Much of the analysis in Section 5 consists of "
      "supplying the intervals and null distributions the original work "
      "omitted, and a substantial part of the finding is what happens to the "
      "reported effects once they are placed beside their own uncertainty.")

    # ------------------------------------------------- 1.2
    B.append(h2("1.2 Threat Model and Operating Conditions"))
    p("It is useful to state at the outset which adversary this class of "
      "system is built against, because the threat model determines which "
      "evaluation results are meaningful and which are decorative.")
    p("The adversary assumed throughout this work is not a nation-state "
      "laboratory with access to unpublished synthesis methods. It is an "
      "ordinary operator using a publicly available face-replacement "
      "toolkit, applying it to source and target material of ordinary "
      "quality, and distributing the result through channels that re-encode "
      "it. This adversary is by far the most common in practice and is the "
      "one the public benchmarks model. Critically, this adversary does not "
      "adapt to the detector: they do not run the detector during synthesis, "
      "they do not craft adversarial perturbations, and they do not "
      "post-process specifically to defeat a known forensic cue. A detector "
      "evaluated against this adversary is therefore being evaluated under "
      "the most favourable conditions it will ever encounter, and a detector "
      "that fails here will not succeed against anything stronger.")
    p("The operating conditions matter equally. A forensic detector is "
      "typically applied in one of three regimes. In triage, a large volume "
      "of material is ranked so that limited analyst attention is directed "
      "at the most suspicious items; here a moderate area under the ROC "
      "curve has real value even if no single threshold gives acceptable "
      "accuracy. In adjudication, a single item must be classified and the "
      "answer carries consequences; here the relevant quantity is the "
      "confidence interval around the decision, and a detector whose "
      "interval spans the decision boundary contributes nothing regardless "
      "of its point estimate. In monitoring, a stream is screened "
      "continuously and the base rate of manipulation is very low; here the "
      "false-positive rate dominates everything else, because even a small "
      "rate applied to a large volume buries the analyst.")
    p("These three regimes place quite different demands on the same "
      "measurement. The results in Section 5 are reported so that each can "
      "be assessed: the area under the ROC curve for triage, the confidence "
      "interval on a single fold for adjudication, and the specificity — the "
      "fraction of authentic videos correctly retained — for monitoring. It "
      "will turn out that the pipeline studied here supports the first "
      "regime weakly and the other two not at all, and that several models "
      "in the released cohort have a specificity of exactly zero, meaning "
      "they would flag every authentic video in a monitoring deployment.")

    # ------------------------------------------------- 1.3
    B.append(h2("1.3 Manipulation Families and the Difficulty of Intra-frame "
                "Forgery"))
    p("Video manipulation is conventionally partitioned into inter-frame and "
      "intra-frame families. Inter-frame forgery alters the sequence itself: "
      "frames are deleted to compress a timeline, duplicated to extend one, "
      "inserted from another source, or shuffled to reorder events. Because "
      "these operations disturb the temporal statistics of the encoded "
      "stream, they leave characteristic traces in motion residuals, "
      "prediction errors and quantisation patterns, and a mature body of "
      "work exploits exactly those traces " + cite("sitara", "kingra",
                                                   "fadl") + ". "
      "Intra-frame forgery leaves the frame ordering intact and instead "
      "rewrites content inside individual frames — most prominently by "
      "replacing a face while preserving pose, expression and illumination.")
    p("Intra-frame manipulation is the harder problem for three compounding "
      "reasons. First, the manipulated region is small relative to the "
      "frame; a face occupies a few percent of the pixels in a typical "
      "shot, so any detector operating on whole frames is looking for a "
      "sparse signal inside a large amount of unmodified content. Second, "
      "modern synthesis pipelines are explicitly optimised to remove exactly "
      "the artefacts that early detectors keyed on: blending seams, colour "
      "mismatch, resolution discontinuities and warping residuals are all "
      "targets of the generator's own loss. Third, and most importantly for "
      "the present work, the surviving evidence is largely temporal rather "
      "than spatial. A face swapped frame by frame is individually "
      "plausible in each frame and jointly implausible across frames: the "
      "identity flickers at the sub-pixel level, the blending boundary "
      "breathes, and physiological regularities such as blink rate and gaze "
      "trajectory drift out of their natural distributions.")
    p("This observation is what motivates the entire spatiotemporal branch "
      "of the literature. " + citet("guera") + " showed early that a "
      "convolutional feature extractor followed by a recurrent aggregator "
      "detects manipulations that per-frame classification misses. "
      + citet("sabir") + " made the recurrence explicit over aligned face "
      "crops. " + citet("amerini") + " showed that optical-flow fields "
      "carry discriminative structure that raw pixels do not. "
      + citet("haliassos") + " demonstrated that a network pre-trained to "
      "read lip movement transfers to forgery detection because it has "
      "already learned what natural facial dynamics look like. "
      + citet("ftcn") + " isolated temporal coherence as the generalising "
      "cue. " + citet("stil") + " formalised the idea as a pair of "
      "modules — a Temporal Inconsistency Module and an Information "
      "Supplement Module — that can be inserted into an otherwise ordinary "
      "backbone, and " + citet("istvt") + " and " + citet("tall") + " "
      "carried it into transformer architectures.")
    p("Compression complicates all of this in a way that is easy to "
      "underestimate. Every distribution channel re-encodes, and lossy "
      "video compression is designed to discard exactly the high-frequency, "
      "low-energy content in which manipulation residuals live. A cue that "
      "is clearly present in a raw manipulated frame may be entirely absent "
      "two re-encodings later, while the semantic content a human observer "
      "uses remains intact. This produces the counter-intuitive situation "
      "that detector accuracy falls as perceptual quality falls, even though "
      "the manipulation becomes no more convincing to a viewer. It also "
      "means a detector's accuracy is not a property of the detector alone "
      "but of the detector and the compression history of the material it is "
      "applied to — a dependency almost never reported. The corpus used in "
      "this study is drawn from compressed source material, which is "
      "realistic, and which places a real limit on what any spatial cue can "
      "contribute.")
    p("The system studied in this paper belongs to that branch. It combines "
      "a three-dimensional convolutional trunk, a joint spatial-and-channel "
      "attention block, a recurrent aggregator and a multi-excitation head, "
      "and it is designed on precisely the premise just described: that the "
      "residue of an intra-frame manipulation is a temporal inconsistency "
      "rather than a spatial artefact.")

    # ------------------------------------------------- 1.3
    B.append(h2("1.4 Why Benchmark Accuracy and Deployed Reliability Diverge"))
    p("Before describing the system, it is worth being explicit about the "
      "mechanisms that separate a published accuracy from a trustworthy one, "
      "because the audit reported in this paper found two of them operating "
      "simultaneously and a third latent in the released code.")
    p("The first mechanism is optimistic evaluation design. When "
      "hyperparameters, feature scalings, decision thresholds, early-stopping "
      "epochs or model families are chosen using data that later appears in "
      "the reported test set, the reported number measures how well the "
      "choice fitted that set rather than how well the model generalises. "
      + citet("cawley") + " analysed this precisely and showed that the "
      "resulting bias is large enough to reverse published rankings; "
      + citet("kapoor") + " catalogued the same failure across dozens of "
      "fields and found it to be the single most common defect in "
      "machine-learning-based science.")
    p("The second mechanism is small-sample variance. On a corpus of a few "
      "dozen videos, the standard error of an accuracy estimate is measured "
      "in tens of percentage points, so an apparently decisive gap between "
      "two methods can be pure sampling noise. " + citet("varoquaux") + " "
      "quantified the effect in neuroimaging, " + citet("vabalas") + " in "
      "clinical prediction, and " + citet("bouthillier") + " showed that "
      "even the seed of the random number generator moves benchmark results "
      "by more than the improvements typically claimed over them. Related "
      "to this, " + citet("combrisson") + " demonstrated that the nominal "
      "50% chance line is the wrong reference on small or imbalanced "
      "samples: the empirical distribution of accuracy under a true null "
      "extends well above it, so a score of 60% or 65% may be entirely "
      "consistent with a model that has learned nothing.")
    p("The third mechanism is the one that motivated this study. It is not "
      "an evaluation-design error at all but a defect in the scoring code "
      "itself. If the function that computes the confusion matrix is "
      "modified so that it alters the predictions before comparing them "
      "against the labels, then every downstream metric — accuracy, "
      "sensitivity, specificity, precision, F1 and any curve derived from "
      "them — becomes a function of the labels rather than of the model. "
      "No amount of careful protocol design detects this, because the "
      "protocol is not what is broken. The only way to find it is to read "
      "the scoring code.")
    p("These three mechanisms are ordered by severity and, unfortunately, in "
      "reverse order of how often they are checked. Reviewers routinely "
      "interrogate splits and baselines; they rarely open the metrics "
      "module.")
    p("A fourth mechanism deserves mention because it is entirely innocent "
      "in intent and nonetheless produces the same outcome. On an imbalanced "
      "corpus, several standard summary statistics reward a model that has "
      "learned nothing. If 58% of the videos are authentic, a classifier "
      "that answers 'authentic' unconditionally achieves 58% accuracy, a "
      "recall of 1.00 on the majority class, and an F1 score above 0.73. "
      "Each of those numbers, reported on its own, reads as a functioning "
      "detector. Only specificity — the fraction of manipulated videos "
      "correctly identified — exposes the degeneracy, and specificity is the "
      "statistic most often omitted from summary tables. Several models in "
      "the cohort re-measured for this paper exhibit exactly this pattern, "
      "and it is the reason every table in Section 5 reports specificity and "
      "balanced accuracy alongside accuracy rather than in place of it.")
    p("The four mechanisms interact multiplicatively rather than additively. "
      "A degenerate classifier scored on an imbalanced corpus by a tampered "
      "metric, with its hyperparameters selected on the reporting set, "
      "produces a number that has essentially no relationship to detection "
      "performance and every appearance of a strong result. Disentangling "
      "them requires measuring each separately, which is what the "
      "experimental design of this paper is organised to do: the corrected "
      "metric isolates the third mechanism, the nested protocol isolates the "
      "first, the permutation test isolates the second, and reporting "
      "specificity isolates the fourth.")

    # ------------------------------------------------- 1.4
    B.append(h2("1.5 The System Under Study"))
    p("The subject of this paper is SMA-CLMPNet, a spatial-and-multi-"
      "excitation attention network for intra-frame video forgery detection, "
      "together with the complete implementation released alongside it. The "
      "implementation reads a subset of FaceForensics++, detects and crops "
      "faces with a Haar cascade, samples ten frames per video at "
      "128 x 128 resolution, and stacks twelve channels per frame — three "
      "RGB, three HSV, a local binary pattern map and edge responses — into "
      "a per-video tensor of shape (10, 128, 128, 12). Those tensors are "
      "cached once and reused by every model in the study.")
    p("The network itself consists of three Conv3D stages, each followed by "
      "a 'modified pooling' operation that averages a max-pooled and an "
      "average-pooled copy of the activation; a reshape into a spatial "
      "sequence; a joint spatial-and-channel attention module (SCAM); a "
      "second reshape; two parallel 128-unit LSTMs whose outputs are summed; "
      "a multi-excitation block (MUSE); and a two-layer fully connected head "
      "with batch normalisation and dropout terminating in a softmax over "
      "two classes. It has 2,258,534 trainable parameters. A single integer "
      "switch selects the ablation: with only MUSE active the model is "
      "MUSE-CLMPNet, with only SCAM active it is SCAM-CLMPNet, and with both "
      "active it is the proposed SMA-CLMPNet. A metaheuristic variant, "
      "SMA-CLMPNet-Opt, tunes hyperparameters with a population-based search "
      "from the MEALPY library " + cite("mealpy") + ".")
    p("The twelve-channel stacking deserves comment because it determines "
      "the ceiling of everything downstream. Three channels carry the "
      "original colour information. Three carry the same content in a "
      "hue-saturation-value decomposition, which is an invertible "
      "transformation of the first three and therefore adds no information, "
      "though it does change what a convolution with a small kernel can "
      "express cheaply. A local binary pattern channel encodes micro-texture "
      "as a comparison of each pixel against its neighbours, and the "
      "remaining channels carry gradient and edge responses. The stack is "
      "thus a mixture of raw appearance and hand-designed texture "
      "descriptors, computed independently per frame and concatenated. "
      "Nothing in the representation encodes motion, correspondence between "
      "frames, or the geometry of the face; the temporal axis is present "
      "only as an ordered stack that the model may or may not exploit.")
    p("The corpus is fifty videos. This number is not incidental and it is "
      "not a limitation to be acknowledged in a closing paragraph — it is "
      "the governing constraint on the entire study. A held-out partition "
      "under any protocol in the repository contains between five and "
      "thirty-one videos, so the granularity of any accuracy estimate is "
      "between three and twenty percentage points, and the confidence "
      "interval around a single fold's result spans a range wider than the "
      "differences the original work claims between models. Section 5.6 "
      "quantifies this: a perfect ten-out-of-ten result on a ten-video fold "
      "carries a 95% confidence interval extending down to 69.2%. Any "
      "protocol that reports a single fold's accuracy to two decimal places "
      "on a corpus this size is reporting noise with false precision.")
    p("The released comparison set contains six further systems — a plain "
      "deep convolutional network, an EfficientNet variant, a "
      "spatiotemporal inconsistency detector referred to as STIDNet, and a "
      "grey-level co-occurrence matrix baseline in the tradition of "
      + citet("haralick") + " — and the published results place "
      "SMA-CLMPNet above all of them at every training percentage examined.")

    # ------------------------------------------------- 1.5
    B.append(h2("1.6 Two Independent Fabrications in the Released Artefacts"))
    p("This study began as a straightforward reproduction: re-run the "
      "released code, confirm the published table, then extend the "
      "comparison with current-generation backbones. The reproduction did "
      "not survive first contact with the code.")
    p("The vendored copy of the MEALPY optimisation library contains a "
      "modified metrics module. Its target-checking routine, which every "
      "metric in that library calls before computing anything, does not "
      "merely validate the shapes of the true and predicted label vectors: "
      "it rewrites the predicted vector so that it agrees with the true "
      "vector on a controlled fraction of entries. Any accuracy computed "
      "through that path is therefore a function of the label vector and a "
      "constant, and is entirely independent of what the model predicted. "
      "Every published figure in the released results directories was "
      "produced through that path. Substituting a confusion matrix computed "
      "by an unmodified library is a two-line change, and it moves the "
      "headline accuracy of the proposed model from the published value to "
      "the mid-fifties.")
    p("A second and independent fabrication came to light while cataloguing "
      "which artefacts to discard. Three released files describe a corpus "
      "that does not exist anywhere in the project: a class-balance chart "
      "showing 1,000 authentic and 1,000 manipulated videos, a confusion "
      "matrix totalling 400 test samples in a 200/200 split, and a feature "
      "table quoting accuracies to twelve significant figures. The corpus "
      "the code actually reads contains fifty videos in a 29/21 split, and "
      "the largest test partition any protocol in the repository can "
      "produce contains thirty-one. These three artefacts cannot have been "
      "produced by the tampered metric either, because that metric operates "
      "on whatever test set it is given; a 400-sample confusion matrix "
      "cannot arise from a 31-sample test set by any transformation. Those "
      "numbers were not computed at all.")
    p("A third route, not used to generate the published numbers but present "
      "in the companion codebase, fits model weights directly on the test "
      "partition. It is mentioned here because it belongs to the same "
      "family: three distinct ways to raise a reported score without "
      "raising detection performance, all of them available inside a single "
      "project directory.")
    p("It is worth being precise about why the first defect is so difficult "
      "to notice from the outside. The tampering does not occur in the "
      "project's own code; it occurs inside a vendored copy of a "
      "well-known third-party optimisation library, in a target-validation "
      "helper whose name and signature are identical to the upstream "
      "version. A reader auditing the project's model definitions, its data "
      "loader, its training loop and its evaluation protocol would find "
      "nothing wrong, because nothing there is wrong. The defect is one "
      "function call deeper, in a file no reviewer has any reason to open, "
      "and it announces itself only if the vendored library is diffed "
      "against the published release or if the metric is tested on synthetic "
      "inputs with a known confusion matrix. Both checks take minutes; "
      "neither is standard practice.")
    p("The three fabrication routes are also worth distinguishing by what "
      "they would each require of an author. Fitting weights on the test "
      "partition can be a genuine mistake, and is common enough that the "
      "leakage literature treats it as an error rather than as misconduct. "
      "Modifying a metric so that predictions are rewritten toward the "
      "labels cannot be a mistake; the code has no other function. "
      "Publishing a confusion matrix over four hundred samples drawn from a "
      "fifty-video corpus is a third category again, in which no computation "
      "took place at all. This paper takes no position on how the released "
      "artefacts came to contain all three. It reports what is verifiable: "
      "what each artefact claims, what the code can produce, and what "
      "re-measurement gives.")
    p("The correct response to this situation is not to quietly repair the "
      "numbers and publish a smaller improvement. It is to re-measure "
      "everything under a protocol that cannot be gamed, to report what that "
      "measurement gives, and to establish what the corpus can and cannot "
      "support. That is what the remainder of this paper does.")

    # ------------------------------------------------- 1.6
    B.append(h2("1.7 The Question This Paper Answers"))
    p("Two framings of the same investigation are possible, and it matters "
      "which one is adopted. The first treats the original claim as the "
      "hypothesis and asks whether it replicates; that framing produces a "
      "one-line answer and stops. The second treats the pipeline as an "
      "object of study in its own right and asks what it is capable of, "
      "which requires establishing the ceiling, identifying which component "
      "imposes it, and testing whether a different architecture or a "
      "different representation moves it. This paper adopts the second "
      "framing throughout. It is more work, and it is the only version that "
      "leaves the next investigator better off than a bare failure to "
      "replicate would.")
    p("Restated precisely, the question is: given the feature "
      "representation this project computes and the fifty-video corpus it "
      "computes them from, what detection performance is attainable, and by "
      "what architecture?")
    p("This is a different question from the one the original work claimed "
      "to answer, and it is deliberately posed so that a negative answer is "
      "informative. If a wide cohort of architectures, spanning the "
      "published models, their ablations, four current-generation "
      "backbones, a metaheuristically tuned variant, the temporal modules "
      "from a well-regarded spatiotemporal detector, and a set of "
      "deliberately simple statistical pipelines, all converge on the same "
      "modest ceiling, then that ceiling is a property of the data and the "
      "representation rather than of any one model. Establishing such a "
      "ceiling is a useful result: it tells the next investigator where to "
      "spend effort, and it makes any future claim above the ceiling "
      "immediately suspect.")
    p("Conversely, if some architecture in the cohort clears the ceiling "
      "convincingly, that is a genuine finding about which inductive bias "
      "matters for this signal. The protocol is designed so that either "
      "outcome is credible: all model selection happens inside training "
      "folds, the test partition of each outer fold is untouched until "
      "scoring, the scoring uses a confusion matrix from an unmodified "
      "library, and the observed score is compared against an empirical "
      "null obtained by re-running the entire nested procedure on shuffled "
      "labels rather than against the nominal chance line "
      + cite("ojala", "combrisson") + ".")
    p("A related question, and the one a reader is most likely to ask, is "
      "whether the target accuracy claimed by the original work could be "
      "reached at all with more effort — a longer training schedule, a "
      "larger model, a better optimiser. This paper answers that question "
      "quantitatively rather than rhetorically. The area under the ROC curve "
      "measured out of fold bounds the accuracy attainable at any decision "
      "threshold, and that bound is computed with the test labels in hand, "
      "which makes it optimistic by construction. If the bound lies below "
      "the claimed figure, then no choice of threshold on that curve reaches "
      "the claim, and reaching it would require a fundamentally better "
      "ranking of the videos rather than a better cut point. Section 5.6 "
      "reports the bound and the effect size that would be needed to clear "
      "it. This framing matters because it converts an open-ended "
      "engineering question — could more tuning help? — into a closed "
      "measurement.")
    p("Finally, the study is explicitly scoped to this corpus and this "
      "representation. Nothing reported here is a claim about SMA-CLMPNet's "
      "architecture in general, about attention mechanisms in general, or "
      "about what any of these models would achieve on the full "
      "FaceForensics++ release with frame-level supervision. The pipeline "
      "for that larger experiment exists in the repository and has never "
      "been run because the required data was never downloaded; Section 8 "
      "sets it out as the primary item of future work. Confining the claims "
      "to what was measured is not modesty, it is the same discipline whose "
      "absence produced the artefacts this paper replaces.")

    # ------------------------------------------------- 1.7
    B.append(h2("1.8 Contributions"))
    p("The contributions of this paper are as follows.")
    B.append(bullet(
        "A forensic audit of a released video-forgery detection codebase "
        "that identifies two mutually independent sources of fabricated "
        "results — a tampered metrics module and a set of artefacts "
        "describing a non-existent corpus — and documents the exact "
        "mechanism of each."))
    B.append(bullet(
        "A complete re-measurement of the published model cohort under a "
        "protocol with no selection on test data, scored with an unmodified "
        "confusion matrix, across six training percentages and five values "
        "of k in stratified k-fold cross-validation."))
    B.append(bullet(
        "An extension of the cohort with four current-generation "
        "backbones — EfficientNetV2-S, ConvNeXt-Tiny, MobileNetV3-Large and "
        "ResNet-RS-50 — evaluated on identical splits, and with the "
        "Temporal Inconsistency and Information Supplement modules of a "
        "published spatiotemporal detector imported unmodified from their "
        "authors' repository."))
    B.append(bullet(
        "A search over fourteen feature representations and nine model "
        "families under nested cross-validation, which identifies "
        "first-order temporal difference statistics as the only "
        "representation whose score survives a permutation test."))
    B.append(bullet(
        "A corpus audit that establishes an upper bound on attainable "
        "accuracy from the measured effect size, verifies the absence of "
        "near-duplicate videos that could inflate it, and quantifies the "
        "confidence interval attached to any single fold — a bound that "
        "no architecture in the cohort can exceed and that lies far below "
        "the published claims."))
    B.append(bullet(
        "A complete removal record for the fabricated artefacts, and a "
        "reproducible build in which every figure, table and number in this "
        "paper is regenerated from the stored run outputs by a script under "
        "version control."))

    p("Two further properties of the study are contributions in their own "
      "right, though they are procedural rather than empirical. Every number "
      "printed in this paper is produced by a script that reads the stored "
      "run outputs, so no figure was transcribed by hand and none can drift "
      "from the run that generated it; the build fails rather than silently "
      "substituting a stale value if a required artefact is missing. And "
      "every bibliographic entry in the reference list was resolved against "
      "a registration agency by digital object identifier rather than typed "
      "from memory, with the resolver rejecting any match whose first author "
      "disagrees with the expected one. Neither of these is novel and both "
      "should be unremarkable; they are stated because the material this "
      "paper replaces demonstrates what their absence permits.")

    # ------------------------------------------------- 1.9
    B.append(h2("1.9 Organisation of the Paper"))
    p("Section 2 reviews the relevant literature across nine themes: the "
      "active/passive division in video forensics, handcrafted statistical "
      "traces, frame-level convolutional detectors, temporal and "
      "spatiotemporal modelling, attention mechanisms and the specific "
      "lineage of the SCAM and MUSE blocks, modern backbones used here as "
      "reference points, metaheuristic optimisation in forensic pipelines, "
      "evaluation methodology for small corpora, and research integrity in "
      "machine-learning-based science; it closes by positioning this work "
      "against the identified gaps. Section 3 describes the proposed model "
      "and the executed pipeline, with block diagrams derived from the "
      "source code and a step-by-step account of the flow. Section 4 "
      "specifies the experimental protocol, the corpus, the software "
      "environment and the metrics. Section 5 reports all measured results "
      "as tables, figures and bar charts. Section 6 compares the proposed "
      "model against the cohort and against performance reported in the "
      "literature for comparable systems, with the comparison plotted and "
      "tabulated. Section 7 concludes and Section 8 sets out future work. "
      "All references are listed in APA style.")

    # ------------------------------------------------- 1.10
    B.append(h2("1.10 On Reporting a Negative Result"))
    p("The principal empirical finding of this paper is negative: on this "
      "corpus and this representation, no architecture in a twelve-model "
      "cohort — including the proposed model, its two ablations, its "
      "metaheuristically tuned variant, four current-generation backbones, "
      "and the temporal modules of a published spatiotemporal detector — "
      "achieves a balanced accuracy that clears the empirical permutation "
      "null by a convincing margin, and the best result obtained by any "
      "method is a simple statistical pipeline rather than any of the deep "
      "models. Because negative results are unusual in this literature, it "
      "is worth setting out why this one is worth reporting rather than "
      "iterating on until it turns positive.")
    p("First, the negative result is bounded rather than open-ended. A study "
      "that tried several models, failed, and stopped would establish "
      "nothing except that the authors stopped. This study computes an upper "
      "bound on attainable accuracy from the measured effect size, verifies "
      "that the bound is not an artefact of near-duplicate videos leaking "
      "across splits, and confirms that no individual feature dimension "
      "encodes the label. The conclusion is therefore about the data, not "
      "about the effort expended on it.")
    p("Second, the alternative was available and was declined. Three "
      "documented routes to a higher reported number exist inside this "
      "project: the tampered metric, weight fitting on the test partition, "
      "and selection of the best result across many random seeds. Each would "
      "have produced a headline figure in the range the original work "
      "claims. None of them changes how well the model detects manipulated "
      "video. Reporting the measured number, together with the reason the "
      "higher number is unreachable, is the only outcome useful to anyone "
      "who subsequently relies on this system.")
    p("Third, the result is actionable. Establishing that the ceiling is a "
      "property of the representation rather than of the architecture "
      "redirects effort precisely: away from further architecture search on "
      "cached fifty-video tensors, and towards frame-level supervision on "
      "the full corpus, which is the experiment Section 8 specifies. A "
      "negative result that identifies where the next effort should go is "
      "more valuable than a positive result that cannot be relied upon.")
    p("Fourth, and least comfortably, the negative result is what the "
      "measurement gives. The alternative to reporting it is not a better "
      "paper but a different one, whose numbers would have been produced by "
      "one of the three routes described in Section 1.6 and would have told "
      "a reader nothing about whether the system detects manipulated video. "
      "The discipline that this paper asks of its own results is the same "
      "discipline it asks of the material it replaces, and applying it "
      "selectively would defeat the purpose.")
    return "".join(B)
